sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eoLTXgJkKCaz66XQ24MrX0/hqdqTNJ8fg9EhrvJC0MI8Bfo9DIOyuqi3ppQx6Kmx7FJT1zJOBCpjKPq1+JEcGzNIk+5FOdbAnVpwf4/YXrVEPR10e/6JJIE+rV5XfhF1XaxltDX+ahZpJJ+x304lwFN4uHemb/J2z6cY5uxCmOcNHWtFCxHU6d77nUQS91j3292MmMZBAMMOx2rQrVvsNzELA+IGXydZd9JAfcsm6fly2RFr0gaNu9p4dA1N0lH16btVE6RoLZElswv9VfkBAP/yTqpqw4lqNqtu4jb16D30DihD07ZThyxqkYu+FgunsSeR06s6pHXdEJBEb2k00cTlNtLBXXkPEk5t3vieeP0oKHpbM9MtEHk+e8ORUzoJ0iR5SHgfbvq+LoQmp765HsGsptHxHx6Y9WpgI3bXUZEI81p48GdBrK09USyYMAjQ9IML6TYSzy3R/pkCZTIZYWmt0m/iWDMLjELOL6xWHbwD8Ckd+xB3+WGmvMwXM4PCB4nv+58GtBBRdsjYs/+Yh/SggfQNCAldW+dEeOkiqI06SpVdaJMpZHRpDcJeQMF7U1YlhS6TzH7zVu82J82yldmRXcVRapx8ygA9GwMmlgRY4y6HH55L2hGvyjNaBPF+1cZLM5qOBdfkcmW1giqQm26CGzRLYRMUyLbs84XRXmU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/They-and-I_2437
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy